### ISSUE TITLE
This is exciting!

### ISSUE THREAD

**Issue by natevw** [hackerb9/Tandy-Terminfo#2]
Haven't tried this yet, but it looks very promising and I'm glad I found it. Thanks for sharing it!

**Comment by natevw** [comment]
Bit more background in case you're interested:

I've got a Raspberry Pi hooked up inside a PiDP-11 which I added the MAX232 chips. I hope to eventually connect straight to the vintage emulated operating system(s) e.g. Unix V6 but in the meantime I've been playing around with the default Raspbian serial hosting stuff. These configs and tips are going to be super helpful.

I have all three models (100/102/200) but right now only the 102 is functional. Hopefully I can test with all three once I figure out what's still ailing the others.

[closing as it's not a real issue]

**Comment by hackerb9** [comment]
I don't own a 100 or 102, so I would love feedback on whether this works on those models as it should.

**Comment by natevw** [comment]
@hackerb9 I put your suggestions into a script I can call when I log in from a "Model T". So far the basics all seem to work (window size for `less`, backspace key, no Unicode in `man` rendering or color sequences from `grep` or `ls` aliases…).

Let me know if there's anything specific you'd like me to test and I'd be happy to give it a try too.

**Comment by hackerb9** [comment]
Window size was the big one, particularly when using the settings for having plus or minus one line of text for the status bar. (For example, have you tried the "td200-s" with the status bar on?) I think my Model 200's telecom program is probably the same other than the number of rows. Are you able to run old BSD "games", like worms (apt install bsdgames) on that small of a screen? What about robotfindskitten?

I see you've already got LANG=C so you won't get raw UTF-8. Which man pages had Unicode characters you were missing? I wonder if anyone has hacked TELCOM to show VT100 graphics or accented characters when appropriate? If the source code is available, it would be easy to add a translation mapping for the Latin1 character set. Otherwise, it probably would require rewriting the graphics characters in the Model 100's ROM. Hmm... just thinking aloud here.)  

Your PiDP-11 is a noble endeavour! Did you know you can also get a free account on genuine mainframe/minicomputer hardware that you can telnet into? (I was just telneted into a CDC 6500 computer made by Seymour Cray before he founded Cray Super Computers). Check out https://livingcomputers.org/Computer-Collection/Online-Systems.aspx  .
